name: "0-6 Label PRs"
on:
  pull_request_target:
    types: [ opened ]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
